name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    name: 'Build and publish to GitHub'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout the source code'
        uses: actions/checkout@v3
      - name: 'Setup Java 12'
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'
      - name: 'Setup Flutter 3.x'
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.x'
          cache: true
      - name: Set up Android SDK
        if: ${{ env.ACT }}
        uses: android-actions/setup-android@v2
      - name: 'Get dependencies'
        run: flutter pub get
      - name: 'Build'
        run: |
          dart run build_runner build --delete-conflicting-outputs
          flutter build apk --split-per-abi
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/apk/release/app-*-release.apk